import { fileURLToPath } from 'node:url';
import { docsConfig } from '@manablox/docs-theme';
import { defineConfig } from 'astro/config';

/** The developer documentation; the pages are the markdown files in `docs/`. */
export default defineConfig(
  docsConfig({
    title: 'Manablox',
    description: 'A configurable, headless CMS.',
    siteUrl: 'https://dev.manablox.io',
    contentRoot: fileURLToPath(new URL('./docs', import.meta.url)),
    // Explicit reading order; each group mirrors a folder under `docs/`.
    sidebar: [
      { label: 'Concepts', slug: 'concepts' },
      {
        label: 'Getting started',
        items: [
          { label: 'Overview', slug: 'getting-started' },
          { label: 'Create a project', slug: 'getting-started/create-a-project' },
          { label: 'Your first space', slug: 'getting-started/first-space' },
          { label: 'Read it from a frontend', slug: 'getting-started/first-request' },
          { label: 'Use it as a dependency', slug: 'getting-started/as-a-dependency' },
        ],
      },
      {
        label: 'Configuration',
        items: [
          { label: 'The config file', slug: 'configuration' },
          { label: 'Environment variables', slug: 'configuration/environment' },
          { label: 'Database', slug: 'configuration/database' },
          { label: 'Storage and media', slug: 'configuration/storage-and-media' },
          { label: 'Logging', slug: 'configuration/logging' },
          { label: 'Mail', slug: 'configuration/mail' },
          { label: 'Content types in code', slug: 'configuration/content-types-in-code' },
          { label: 'Resources in code', slug: 'configuration/resources-in-code' },
          { label: 'Controls', slug: 'configuration/controls' },
        ],
      },
      {
        label: 'The content model',
        items: [
          { label: 'How content is organised', slug: 'content-model' },
          { label: 'Field types', slug: 'content-model/field-types' },
          { label: 'Locales and translations', slug: 'content-model/localisation' },
          { label: 'Drafts, publishing and versions', slug: 'content-model/publishing' },
        ],
      },
      {
        label: 'The admin',
        items: [
          { label: 'A tour', slug: 'admin' },
          { label: 'Keyboard shortcuts', slug: 'admin/keyboard' },
          { label: 'Spaces and members', slug: 'admin/spaces' },
          { label: 'Users and roles', slug: 'admin/users-and-roles' },
          { label: 'Single sign-on', slug: 'admin/sso' },
          { label: 'API keys', slug: 'admin/api-keys' },
          { label: 'Building content types', slug: 'admin/content-types' },
          { label: 'Editing content', slug: 'admin/editing-content' },
          { label: 'Databags', slug: 'admin/databags' },
          { label: 'Assets', slug: 'admin/assets' },
          { label: 'Menus', slug: 'admin/menus' },
          { label: 'Redirects', slug: 'admin/redirects' },
          { label: 'Tags', slug: 'admin/tags' },
          { label: 'Workflows', slug: 'admin/workflows' },
          { label: 'Webhooks', slug: 'admin/webhooks' },
          { label: 'Activity', slug: 'admin/activity' },
          { label: 'AI', slug: 'admin/ai' },
          { label: 'Notifications and approvals', slug: 'admin/notifications' },
          { label: 'Moving a space', slug: 'admin/transfer' },
          { label: 'Backups', slug: 'admin/backups' },
          { label: 'Environments', slug: 'admin/environments' },
        ],
      },
      {
        label: 'Delivering content',
        items: [
          { label: 'Overview', slug: 'delivery' },
          { label: 'GraphQL', slug: 'delivery/graphql' },
          { label: 'REST', slug: 'delivery/rest' },
          { label: 'The SDK', slug: 'delivery/sdk' },
          { label: 'Preview and the visual editor', slug: 'delivery/preview' },
          { label: 'The public API', slug: 'delivery/public-api' },
          { label: 'Caching', slug: 'delivery/caching' },
        ],
      },
      {
        label: 'Designed sites',
        items: [
          { label: 'Overview', slug: 'site' },
          { label: 'Running the site process', slug: 'site/running' },
          { label: 'The design model', slug: 'site/designs' },
          { label: 'Themes in code and theme files', slug: 'site/themes' },
          { label: 'Domains, redirects, share links and forms', slug: 'site/forms-links' },
          { label: 'Permissions and RPC', slug: 'site/api' },
        ],
      },
      {
        label: 'Guides',
        items: [
          { label: 'Scaffold a frontend', slug: 'guides/scaffold-a-frontend' },
          { label: 'A Vite + Vue SSR frontend', slug: 'guides/vite-vue-ssr' },
          { label: 'A Nuxt frontend', slug: 'guides/nuxt' },
        ],
      },
      {
        label: 'Extending',
        items: [
          { label: 'Custom field types', slug: 'extending/custom-field-types' },
          { label: 'Plugins', slug: 'extending/plugins' },
          { label: 'Plugin contract', slug: 'extending/plugin-contract' },
          { label: 'Plugin dependencies', slug: 'extending/dependencies' },
          { label: 'Extension points', slug: 'extending/extension-points' },
          { label: 'Lifecycle and channels', slug: 'extending/lifecycle' },
          { label: 'Server routes', slug: 'extending/server-routes' },
          { label: 'Server modes', slug: 'extending/server-modes' },
          { label: 'CLI contributions', slug: 'extending/cli' },
          { label: 'Admin plugins', slug: 'extending/admin-plugins' },
          { label: 'Admin slots', slug: 'extending/admin-slots' },
          { label: 'Plugin slots and apis', slug: 'extending/plugin-slots' },
          { label: 'Admin SDK', slug: 'extending/admin-sdk' },
          { label: 'Live preview channels', slug: 'extending/live-preview-channels' },
          { label: 'Block extensions', slug: 'extending/block-extensions' },
          { label: 'Plugin permissions', slug: 'extending/permissions' },
          { label: 'Plugin controls', slug: 'extending/controls' },
          { label: 'Plugin services', slug: 'extending/services' },
          { label: 'Plugin procedures', slug: 'extending/rpc' },
          { label: 'Plugin jobs', slug: 'extending/jobs' },
          { label: 'Data providers', slug: 'extending/data-providers' },
          { label: 'Storage drivers', slug: 'extending/storage-drivers' },
          { label: 'Workflow actions', slug: 'extending/workflow-actions' },
          { label: 'Hooks', slug: 'extending/hooks' },
        ],
      },
      {
        label: 'Deployment',
        items: [
          { label: 'Production stack', slug: 'deployment' },
          { label: 'Operations', slug: 'deployment/operations' },
          { label: 'Security', slug: 'deployment/security' },
          { label: 'Database roles', slug: 'deployment/database-roles' },
          { label: 'CI and releases', slug: 'deployment/releases' },
          { label: 'Premium plugin licenses', slug: 'deployment/licenses' },
          { label: 'Running under a control layer', slug: 'deployment/control-layer' },
          { label: 'Moving from SQLite to Postgres', slug: 'deployment/sqlite-to-postgres' },
          { label: 'Updating', slug: 'deployment/updating' },
        ],
      },
      {
        label: 'Reference',
        items: [
          { label: 'Architecture', slug: 'reference/architecture' },
          { label: 'Data model', slug: 'reference/data-model' },
          { label: 'Control API', slug: 'reference/control-api' },
          { label: 'Error keys', slug: 'reference/errors' },
          { label: 'HTTP API', slug: 'reference/http-api' },
          { label: 'Licensing', slug: 'reference/licensing' },
          { label: 'Testing', slug: 'reference/testing' },
          { label: 'Contributing', slug: 'reference/contributing' },
        ],
      },
    ],
  }),
);
